# Generated by Django 2.1.1 on 2020-01-13 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('engine', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=32)),
                ('IP_address', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='browser',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rk.Computer'),
        ),
    ]
